common:
    data_path: "/home/will/data/HBA/PCD2/"
    pcd_prefix: "keyframe/"
    pose_file_name: "pose.txt"
    total_layer_num: 3
    pcd_name_fill_num: 6    # set 5 for kitti07 and 0 for park
    thread_num: 16
    layer_limit: 2          # the maximum number of voxel recut times in LiDAR BA.

    downsample_size: 0.1    # leaf size used for point cloud downsampling of each LiDAR scan.
    voxel_size: 4.0         # initial voxel size used in LiDAR BA
    eigen_ratio: 0.1        # threshold used to determine whether this voxel contains valid plane feature.
    reject_ratio: 0.05      # threshold used to reject the largest certain amount of voxels (residuals) used in optimization.

    # 非重合平面之间变为重合的解决方案: https://github.com/hku-mars/HBA/issues/22
    # 我的建议是试试更严格的参数，比如voxel_size=1m, eigen_ratio=0.05, downsample_size=0.05.
    # downsample_size: 0.05
    # voxel_size: 1.0
    # eigen_ratio: 0.05

mme:
    enable_mme: true
    downsample_size: 0.1
    search_radius: 0.3
    threads_num: 20

visualize:
    downsample_size: 0.1
    marker_size: 0.5
