common:
    data_path: "/home/sam/Desktop/kitti07/"
    pcd_prefix: "pcd/"
    pose_file_name: "pose.txt"
    total_layer_num: 3
    pcd_name_fill_num: 5    # set 5 for kitti07 and 0 for park
    thread_num: 16
    layer_limit: 2          # the maximum number of voxel recut times in LiDAR BA.

    downsample_size: 0.1    # leaf size used for point cloud downsampling of each LiDAR scan.
    voxel_size: 4.0         # initial voxel size used in LiDAR BA
    eigen_ratio: 0.1        # threshold used to determine whether this voxel contains valid plane feature.
    reject_ratio: 0.05      # threshold used to reject the largest certain amount of voxels (residuals) used in optimization.

mme:
    enable_mme: false
    downsample_size: 0.1
    search_radius: 0.3
    threads_num: 20

visualize:
    downsample_size: 0.1
    marker_size: 0.5
