common:
    data_path: "/home/sam/Desktop/kitti07/"
    total_layer_num: 3
    pcd_name_fill_num: 5    # set 5 for kitti07 and 0 for park
    thread_num: 16

visualize:
    downsample_size: 0.1
    marker_size: 0.5
